# This workflow will upload a Python Package to PyPI when a release is created
name: Menataur

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel twine  # Install necessary tools for building and publishing
          pip install colorama  # Install your package dependencies

      - name: Build release distributions
        run: python setup.py sdist bdist_wheel

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists